# Generated by Django 3.2.16 on 2022-11-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_fileupload_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='test',
        ),
    ]
