# Generated by Django 3.2.16 on 2022-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(null=True, related_name='rooms', to='blog.Amenity'),
        ),
    ]
