# Generated by Django 3.2.16 on 2022-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='test',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
