# Generated by Django 3.2.16 on 2022-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_fileupload_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='test',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='latitude',
            field=models.FloatField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='longitude',
            field=models.FloatField(blank=True, default=0, max_length=200),
        ),
    ]
