# Generated by Django 3.2.16 on 2022-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20221123_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='tmp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
