# Generated by Django 3.2.16 on 2022-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20221124_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filereceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tmp', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
